### Custom layers
What happens if you need a type of layer that doesn't exist in the general deep learning framework?


In [1]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

In [2]:
# a module with no parameters of it's own.
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

By doing this we can add our own layer into a larger module.

In [4]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

c:\Users\Scott Hamilton\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(2.3283e-09, grad_fn=<MeanBackward0>)

What about adding layers with parameters?
Use nn.Parameters

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [9]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.6632, -1.9310,  1.4318],
        [ 2.3552,  0.7275,  0.3910],
        [-0.9055, -0.1495,  2.0210],
        [ 0.1733, -1.1327,  0.5337],
        [ 1.3498,  0.3289, -1.4905]], requires_grad=True)

In [10]:
# an example with a different input and including the bias
linear2 = MyLinear(6,2)
linear2.weight, linear2.bias

(Parameter containing:
 tensor([[ 0.3474,  0.9979],
         [ 1.7073,  0.1224],
         [ 1.2717,  0.2883],
         [ 0.2801, -0.9597],
         [-0.9421, -0.2296],
         [-0.5012,  0.8115]], requires_grad=True),
 Parameter containing:
 tensor([-1.2514,  1.8368], requires_grad=True))

In [11]:
# Using forward Propogation
linear(torch.rand(2,5))

tensor([[1.2429, 0.0000, 1.2015],
        [0.7308, 0.0000, 2.3930]])