### Source: https://d2l.ai/chapter_preliminaries/ndarray.html

In [1]:
#imports
import torch


c:\Users\Scott Hamilton\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
x =  torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
#the size of the tensor
x.numel()

12

In [5]:
#transforms x from a 12, tensor to a 3,4 tensor 
#12 groups of one to 3 groups of 4
X = x.reshape(3,4)
print(X)
print("size of x: ", X.numel())

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
size of x:  12


In [ ]:
#this does the same thing as the previous block.
capitalx = x.reshape(-1,4) #or x.reshape(3,-1)

In [6]:
torch.zeros((2,3,4))
#torch.ones()
#torch.randn

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#tensor with custom values
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])