In [11]:
#First attempt at creating a nn from scratch

import torch
import numpy

letters = "abcdefghijklmnopqrstuvwxyz"

lst = list(letters)

inputTensor = torch.zeros(26)


print(lst)
print(inputTensor)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
range(0, 26)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])


In [20]:
def isVowel(index):
    return {charToInt('a'),charToInt('e'),charToInt('i'),charToInt('o'),charToInt('u')}.__contains__(index)

def charToInt(char):
    return ord(char) - 97

def charToTensor(char):
    tensor = torch.zeros(26)
    tensor[charToInt(char)] = 1
    return tensor

In [13]:
class NN(torch.nn.Module):
    def __init__(self,input_dim=26,output_dim=2):
        super(NN,self).__init__()
        self.lin1 = torch.nn.Linear(input_dim,output_dim)

    def forward(self, input):
        output = self.lin1(input)
        return output

In [14]:
model = NN()

def weightsInit(model):
    for m in model.modules():
        if isinstance(m,torch.nn.Linear):
            m.weight.data.normal_(0,1)
weightsInit(model)

In [15]:
loss_func = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.02,momentum=0.9)

In [30]:
from random import randrange


epochs = 2000
for i in range(epochs):
    for j in range(letters.__sizeof__()):
        letter = letters[randrange(26)]
        desiredOutput = torch.Tensor([0,1])
        if(isVowel(charToInt(letter))):
            desiredOutput = torch.Tensor([1,0])

        optimizer.zero_grad()
        output = model(charToTensor(letter))
        loss = loss_func.forward(output,desiredOutput)
        loss.backward()
        optimizer.step()
        
    if i% 500 == 0:
        print("Epoch: {0}, Loss: {1}, ".format(i, loss.data.numpy()))



Epoch: 0, Loss: 0.13221104443073273, 
Epoch: 500, Loss: 7.105427357601002e-15, 
Epoch: 1000, Loss: 2.3092638912203256e-14, 
Epoch: 1500, Loss: 8.881784197001252e-15, 


In [31]:
print(model(charToTensor('a')))
print(model(charToTensor('b')))
print(model(charToTensor('c')))
print(model(charToTensor('d')))
print(model(charToTensor('e')))

tensor([1.0000e+00, 2.9802e-07], grad_fn=<AddBackward0>)
tensor([-5.9605e-08,  1.0000e+00], grad_fn=<AddBackward0>)
tensor([1.1921e-07, 1.0000e+00], grad_fn=<AddBackward0>)
tensor([-2.9802e-08,  1.0000e+00], grad_fn=<AddBackward0>)
tensor([ 1.0000e+00, -3.5763e-07], grad_fn=<AddBackward0>)
