In [1]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.optim as optim
import numpy as np

X = torch.Tensor([[0,0],[0,1],[1,0],[1,1]])
Y = torch.Tensor([0,0,0,1]).view(-1,1)

In [2]:
class AND(nn.Module):
    def __init__(self,input_dim=2,output_dim=1):
        super(AND,self).__init__()
        self.lin1 = nn.Linear(input_dim,output_dim)

    def forward(self, x):
        x = self.lin1(x)
        return x
model = AND()


In [3]:
def weights_init(model):
    for m in model.modules():
        if isinstance(m,nn.Linear):
            m.weight.data.normal_(0,1)
weights_init(model)

In [4]:
loss_func = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.02,momentum=0.9)

In [5]:
epochs = 2001
steps = X.size(0)
for i in range(epochs):
    for j in range(steps):
        data_point = np.random.randint(X.size(0))
        x_var = Variable(X[data_point],requires_grad=False)
        y_var = Variable(Y[data_point],requires_grad=False)

        optimizer.zero_grad()
        y_hat = model(x_var) # predicted y's
        loss = loss_func.forward(y_hat,y_var)
        loss.backward()
        optimizer.step()
    
    if i% 500 == 0:
        print("Epoch: {0}, Loss: {1}, ".format(i, loss.data.numpy()))

Epoch: 0, Loss: 0.9076581001281738, 
Epoch: 500, Loss: 0.04806326702237129, 
Epoch: 1000, Loss: 0.027184326201677322, 
Epoch: 1500, Loss: 0.14368939399719238, 
Epoch: 2000, Loss: 0.1805325150489807, 


In [7]:
print(model(torch.tensor([0,0]).float()))
print(model(torch.tensor([0,1]).float()))
print(model(torch.tensor([1,0]).float()))
print(model(torch.tensor([1,1]).float()))

tensor([-0.4184], grad_fn=<AddBackward0>)
tensor([0.2091], grad_fn=<AddBackward0>)
tensor([0.1230], grad_fn=<AddBackward0>)
tensor([0.7505], grad_fn=<AddBackward0>)
